multicake/cakeapp/urls.py
from django.urls import path
from .views import MainView, ProductListView, DeliveryView, load_more, ProductDetailView, FillingView,\
    PortfolioView, CantactView, ProductFilterView

app_name = 'cakeapp'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('fillings/', FillingView.as_view(), name='fillings'),
    path('portfolio/', PortfolioView.as_view(), name='portfolio'),
    path('product_filter/', ProductFilterView.as_view(), name='product_filter'),
    path('cantact/', CantactView.as_view(), name='cantact'),
    path('product/<int:pk>', ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>', ProductDetailView.as_view(), name='product'),
    path('delivery/', DeliveryView.as_view(), name='delivery'),
    path('load/', load_more, name='load')

]

multicake/multicake/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from cakeapp.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap,

}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('cakeapp.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

multicake/cakeapp/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse




class Banner(models.Model):
    image = models.ImageField(_('Rasm'), upload_to='Banner')


    class Meta:
        verbose_name = 'Banner'
        verbose_name_plural = 'Bannerlar'


class Logo(models.Model):
    image = models.ImageField(_('Rasm'), upload_to='Logo')


    class Meta:
        verbose_name = 'Logo'
        verbose_name_plural = 'Logo'



class CakeType(models.Model):
    name = models.CharField(_('Nomi'), max_length=100)
    image = models.ImageField(_('Rasm'), upload_to='To\'rt turlari')

    class Meta:
        verbose_name = 'To\'rt turi'
        verbose_name_plural = 'To\'rt turlari'

    def __str__(self) -> str:
        return self.name



class Cake(models.Model):
    name = models.CharField(_('Nomi'), max_length=100)  
    type = models.ForeignKey(CakeType, on_delete=models.CASCADE, verbose_name=_('Turi'))
    price_for_kg = models.CharField(_('1 kg narxi'), max_length=200)
    min_amount_kg = models.PositiveIntegerField(_('Eng kam buyurtma miqdori (kg)'))
    image = models.ImageField(_('Rasm'), upload_to='To\'rtlar')

    def get_absolute_url(self):
        return reverse("cakeapp:product", args=[self.id])

    class  Meta:
        verbose_name = 'To\'rt'
        verbose_name_plural = 'To\'rtlar'

    def __str__(self) -> str:
        return self.name


class Filling(models.Model):
    name = models.CharField(_('Nomi'), max_length=100)
    composition = models.CharField(_('Tarkibi'), max_length=255)
    image = models.ImageField(_('Rasm'),blank=True, null=True, upload_to='Nachinka')

    def get_absolute_url(self):
        return reverse("cakeapp:fillings", args=[self.id])

    class Meta:
        verbose_name = 'Nachinka'
        verbose_name_plural = 'Nachinkalar'


    def __str__(self) -> str:
        return self.name

    
class Portfolio(models.Model):
    image = models.ImageField(_('Rasm'), upload_to='Biznig-ishlar')


    class Meta:
        verbose_name = 'Bizning ish'
        verbose_name_plural = 'Bizning ishlar'

    
class Contact(models.Model):
    number = models.CharField(_('Telefon raqam'), max_length=23)
    email = models.EmailField()
    adress = models.CharField(_('Joylashuv manzili'), max_length=250)
    status = models.BooleanField(_('Holati'), default=False)
    instagram = models.URLField(_('Instagram uchun link'),)
    telegram = models.URLField(_('Telegram uchun link'))


    class Meta:
        verbose_name = 'Kontakt'
        verbose_name_plural = 'Kontaktlar'


    def __str__(self) -> str:
        return str(self.number)


@receiver(pre_save, sender=Contact)
def my_handler(sender, instance=None, created=False, **kwargs):

    if str(instance)[0:4] != '+998' or len(str(instance)) < 13:
        raise ValueError(_("Raqam noto\'g\'ri kiritildi"))



class Order(models.Model):


    class DeliveryTypes(models.IntegerChoices):
        self_delivery = 1, _('Olib ketish')
        delivery = 2, _('Yetkazib berish')


    date = models.DateField(_('Qaysi kunga'))
    cake = models.ForeignKey(Cake, on_delete=models.CASCADE, verbose_name='To\'rt')
    number = models.CharField(_('Telefon raqam'), max_length=13)
    how_many_kg = models.PositiveIntegerField(_('Kerakli hajim (kg)'))
    filling = models.ForeignKey(Filling, on_delete=models.CASCADE, verbose_name='Nachinka')
    writing = models.CharField(_('To\'rt ustidagi yozuv'), max_length=255)
    type_of_delivery = models.PositiveIntegerField(_('Yetkazib berish turi'),  default=DeliveryTypes.self_delivery, choices=DeliveryTypes.choices)


    class Meta:
        verbose_name = 'Buyurtma'
        verbose_name_plural = 'Buyurtmalar'


    def __str__(self) -> str:
        return f'{self.number} -> {self.cake.name}  {self.date}'

multicake/cakeapp/forms.py
from django.forms import ModelForm
from .models import Order


class OrderForm(ModelForm):

    class Meta:
        model = Order
        fields = ['date', 'cake', 'number', 'how_many_kg', 'filling', 'writing', 'type_of_delivery']

multicake/cakeapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.conf import settings
from django.views.generic import TemplateView
from . import forms
from . import models
from django.views import generic
from django.http import JsonResponse
import telegram_send

from .forms import OrderForm
from .models import Filling, Portfolio, Cake, CakeType



class MainView(generic.TemplateView):

    template_name = 'index.html'


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['fillings'] = Filling.objects.all().order_by('-id')[0:3]
        context['portfolio'] = Portfolio.objects.all().order_by('-id')[0:6]
        context['total_fillings'] = Filling.objects.count()
        context['total_portfolio'] = Portfolio.objects.count()
        context['cakes'] = models.CakeType.objects.all()[:9]
        context['banner'] = models.Banner.objects.all().order_by('-id')

        return context


class ProductFilterView(generic.TemplateView):

    template_name = 'product_filter.html'


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['cakes'] = models.CakeType.objects.all().order_by('-id')[:9]

        return context


class PortfolioView(generic.TemplateView):

    template_name = 'portfolio.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['portfolio'] = Portfolio.objects.all().order_by('-id')[0:3]
        context['total_portfolio'] = Portfolio.objects.count()

        return context


class FillingView(generic.TemplateView):

    template_name = 'filling.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['fillings'] = Filling.objects.all().order_by('-id')[0:3]
        context['total_fillings'] = Filling.objects.count()

        return context


class ProductListView(TemplateView):
    template_name = 'product.html'

    def get_context_data(self, **kwargs):
        product = Cake.objects.filter(type__id=self.kwargs['pk'])[::-1]
        product_paginator = Paginator(product, 9)
        page_number = self.request.GET.get('page')
        context = super().get_context_data(**kwargs)
        context['cakeproduct'] = product_paginator.get_page(page_number)
        context['caketype'] = CakeType.objects.get(id=self.kwargs['pk'])
        context['caketypes'] = CakeType.objects.all()
        return context


class ProductDetailView(generic.DetailView):
    template_name = 'product_detail.html'
    model = Cake
    form_class = forms.OrderForm


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cake'] = Cake.objects.get(id = self.kwargs['pk'])
        context['caketype_id'] = context['cake'].type.id
        context['fillings'] = Filling.objects.all()
        form = forms.OrderForm(self.request.POST or None)

        context["form"] = form

        return context


    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data()

        if context["form"].is_valid():
            context["form"].save()
            filling_id = context['form']['filling'].value()
            cake_id = context['form']['cake'].value()
            delivery_id = context['form']['type_of_delivery'].value()

            filling = models.Filling.objects.get(id=filling_id)
            cake = models.Cake.objects.get(id=cake_id)
            caketype = cake.type

            if int(delivery_id) == 1:
                delivery = 'Olib ketish'
            else:
                delivery = 'Yetkazib berish'


            array = [f"Sizga yangi buyurtma kelib tushdi:✅ \n\n🎂To'rtning turi: {caketype.name} \n🎂To'rt nomi: {cake.name} \n📅Kuni:  {context['form']['date'].value()} \n📞Buyurtmachi raqami:  {context['form']['number'].value()} \n⚖️Necha kg:  {context['form']['how_many_kg'].value()} \n🍰Nachinka:  {filling.name} \n📝To\'rt ustiga yozuv: {context['form']['writing'].value()} \n🚕Yetkazish turi:  {delivery}"]


            telegram_send.send(messages=array)


            return redirect('/')
        else:
            form = OrderForm()
            return render(request, 'product_detail.html', {'form': form})



    



def load_more(request):

    if request.GET.get('offset'):
        offset = request.GET.get('offset')
        offset_int = int(offset)
        limit = 2
        fillings = list(Filling.objects.values().order_by('-id')[offset_int:offset_int+limit])

        for filling in fillings:
            filling['image'] = settings.MEDIA_URL + str(filling['image'])
            print(filling['image'])

        data = {
            'fillings': fillings
        }

    elif request.GET.get('offset-4'):
        offset = request.GET.get('offset-4')
        offset_int = int(offset)
        limit = 4
        fillings = list(Filling.objects.values().order_by('-id')[offset_int:offset_int+limit])

        for filling in fillings:
            filling['image'] = settings.MEDIA_URL + str(filling['image'])
            print(filling['image'])

        data = {
            'fillings': fillings
        }

    elif request.GET.get('offset-product'):
        offset = request.GET.get('offset-product')
        offset_int = int(offset)
        limit = 1
        fillings = list(Filling.objects.values().order_by('-id')[offset_int:offset_int+limit])

        for filling in fillings:
            filling['image'] = settings.MEDIA_URL + str(filling['image'])
            print(filling['image'])

        data = {
            'fillings': fillings
        }

    else:
        limit = 3
        offsetPort = request.GET.get('offset-portfolio')
        offsetPort_int = int(offsetPort)
        portfolio = list(Portfolio.objects.values().order_by('-id')[offsetPort_int:offsetPort_int+limit])

        for port in portfolio:
            port['image'] = settings.MEDIA_URL + str(port['image'])
            print(port['image'])

        data = {
            'portfolio': portfolio
        }

    
    return JsonResponse(data=data)


class CantactView(TemplateView):
    template_name = "map.html"


class DeliveryView(TemplateView):
    template_name = "delivery.html"

multicake/cakeapp/templates/base.html
<!DOCTYPE html>
{% load static i18n %}
<html lang="ru">

<head>
  <meta charset="UTF-8" />
  <meta name="description" property="og:description" content="Торты на заказ в Ташкенте | Цены и фото | Большой каталог товаров, Buyurtma uchun To'rtlar | To'rtlarning Narxlari va Rasmlari | To'rtlarning keng turlari">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="author" content="Saidaziz Sharifof">
  <meta name="keywords" content="Свадебные торты, Корпаративные торты, Торты для мужчин, Торты для женщин, Домашняя выпечка, Муссовые торты, Романтические торты, Пирожные и десерты, Nikox to'rtlari, Erkaklar uchun to'rt, Ayollar uchun to'rt, Bolalar uchun to'rt">
  <meta name="robots" content="index, follow, noodp">
  <meta name="googlebot" content="index, follow">
  <meta name="google" content="notranslate">
  <title>{% block title %}
    Торты на заказ в Ташкенте | Цены и фото | Большой каталог товаров
  {% endblock %}</title>
  <link rel="stylesheet" href="{% static 'style/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'style/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'style/style.css' %}">
  <link rel="stylesheet" href="{% static 'style/media.css' %}">
  <link rel="shortcut icon" href="{% static 'img/logo-foot.svg' %}" type="image/x-icon">


  <script src="https://cdn.jsdelivr.net/gh/cferdinandi/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js" ></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>

</head>

<body>
  <header class="header" id="header">
    <div class="container-fluid">
      <nav class="navbar header__nav">
        <div class="header__logo">
          <a class="header__logo logo" href="/"><img src="{{ logo.image.url }}" alt="лого" class="logo-img" /></a>
        </div>
        <div class="header__menu">
          <ul class="navbar-nav menu">
            <li class="nav-item active">
              <a class="menu__link" href="{% url 'cakeapp:product_filter' %}">{% trans "To'rtlar" %}</a>
            </li>
            <li class="nav-item">
              <a class="menu__link" href="{% url 'cakeapp:fillings' %}">{% trans "Nachinka" %}</a>
            </li>
            <li class="nav-item">
              <a class="menu__link" href="{% url 'cakeapp:delivery' %}">{% trans "Yetkazib berish" %}</a>
            </li>
            <li class="nav-item">
              <a class="menu__link" href="{% url 'cakeapp:portfolio' %}">{% trans "Qilgan ishlarimiz" %}</a>
            </li>
            <li class="nav-item">
              <a class="menu__link" href="{% url 'cakeapp:cantact' %}">{% trans "Kantakt" %}</a>
            </li>
          </ul>
        </div>
        <div class="contacts d-flex align-items-center">
          <div class="contacts__desc">
            <a href="tel:{{ cantact.number }}" class="contacts__phone">{{ cantact.number }}</a>
            <p class="contacts__info">{% trans "Ish vaxtimiz 10:00 dan 20:00 gacha" %}</p>
          </div>
          <div class="contacts__link">
            <a href="{{ cantact.instagram }}" class="contacts__link-social">
              <img src="{% static 'img/contact-social/instagram-con.svg' %}" alt="instagram" class="contacts__link-social-img" />
            </a>
            <a href="{{ cantact.telegram }}" class="contacts__link-social">
              <img src="{% static 'img/contact-social/telegram-con.svg' %}" alt="telegram" class="contacts__link-social-img" />
            </a>
          </div>
        </div>
        <div class="flex flex-col justify-center space-y-1 items-center tillarUzbRus">
            <!-- <a href="#" class="header__uzb">UZB</a>
            <a href="#" class="header__rus">РУС</a> -->
        <form class="header__lang" action="{% url 'set_language' %}" method="post">
           {% csrf_token %}
          <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}" />
          <input name="language" type="hidden" value="uz" />
          <input class="header__lang-link" type="submit" value="Uz" />
        </form>
        <form class="header__lang" action="{% url 'set_language' %}" method="post">
           {% csrf_token %}
          <input name="next" type="hidden" value="{{ request.get_full_path|slice:'3:' }}" />
          <input name="language" type="hidden" value="ru" />
          <input class="header__lang-link" type="submit" value="Ru" />
        </form>
          </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
      </nav>
    </div>
    
  </header>
  <main class="main" id="main">

    {% block content %}


    
    {% endblock %}



  </main>
  <footer class="footer" id="footer">
    <div class="container">
      <div class="footer__content d-flex justify-content-between">
        <div class="footer__content-info footer__content-info-dist">
          <p class="footer__content-title">{% trans "Harakatlanish" %}</p>
          <ul class="footer__content-nav p-0 m-0">
            <li><a href="{% url 'cakeapp:product_filter' %}" class="footer__content-link footer__content-link-dist">{% trans "To'rtlar" %}</a></li>
            <li>
              <a href="{% url 'cakeapp:fillings' %}" class="footer__content-link footer__content-link-dist">{% trans "Nachinka" %}</a>
            </li>
            <li><a href="{% url 'cakeapp:delivery' %}" class="footer__content-link footer__content-link-dist">{% trans "Yetkazib berish" %}</a></li>
            <li><a href="{% url 'cakeapp:portfolio' %}" class="footer__content-link footer__content-link-dist">{% trans "Qilgan ishlarimiz" %}</a></li>
            <li><a href="{% url 'cakeapp:cantact' %}" class="footer__content-link footer__content-link-dist">{% trans "Kantakt" %}</a></li>
          </ul>
        </div>
        <div class="footer__content-info">
          <div class="footer__contacts-content">
            <p class="footer__content-title">{% trans "Kantaktlarimiz" %}</p>
            <ul class="footer__content-nav p-0 m-0">
              <li>
                <p class="footer__content-link footer__content-desc footer__content-link-left">
                  {{ cantact.adress }}
                </p>
              </li>
              <li>
                <a href="tel:{{ cantact.number }}" class="footer__content-link">{{ cantact.number }}</a>
              </li>
              <li>
                <a href="{{ cantact.email }}" class="footer__content-link">{{ cantact.email }}</a>
              </li>
            </ul>
          </div>
          <div class="footer__content-info footer__content-info-margin">
            <p class="footer__content-title-margin">{% trans "Satsial a'loqa" %}</p>
            <div class="footer__social-cent d-flex align-items-center justify-content-start">
              <a href="{{ cantact.instagram }}" class="footer__content-social-link">
                <img src="{% static 'img/contact-social/instagram-con.svg' %}" alt="instagram" class="footer__content-social-img" />
              </a>
              <a href="{{ cantact.telegram }}" class="footer__content-social-link">
                <img src="{% static 'img/contact-social/telegram-con.svg' %}" alt="telegram" class="footer__content-social-img" />
              </a>
            </div>
          </div>
        </div>
        <div class="footer__logo d-flex align-items-center">
          <a href="/">
            <a class="header__logo logo" href="/"><img src="{{ logo.image.url }}" alt="лого" class="logo-img" /></a>
          </a>
        </div>
      </div>
    </div>
  </footer>






  <script>
    const loadBtn = document.getElementById('btn-filling');
    const spinner = document.getElementById('spinner-filling');
    const total = JSON.parse(document.getElementById('json-total').textContent);
    const alert = document.getElementById('alert-filling');
    
    const loadBtnPort = document.getElementById('btn-portfolio');
    const spinnerPort = document.getElementById('spinner-portfolio');
    const totalPort = JSON.parse(document.getElementById('json-total-port').textContent);
    const alertPort = document.getElementById('alert-portfolio');

    function loadmoreFilling() {
        var _current_item = $('.single_content').length
        const content_container = document.getElementById("content");
        $.ajax({
            url: '{% url "cakeapp:load" %}',
            type: 'GET',
            data: {
                'offset': _current_item
            },
            beforeSend: function () {
                loadBtn.classList.add('not-visible');
                spinner.classList.remove('not-visible'); 
            },
            success: function (response) {
                const data = response.fillings
                spinner.classList.add('not-visible')
                data.map((filling, index) => {

                    if (index%2 == 0) {
                   
                      content_container.innerHTML += `

                                <div class="single_content baked__right d-flex align-items-center justify-content-end">
                                  <div class="baked__info1">
                                    <h4 class="baked__title text-uppercase fw-bold">${filling.name}</h4>
                                    <p class="baked-info">
                                      Состав: ${filling.composition}
                                    </p>
                                  </div>
                                  <div class="baked__left-img">
                                    <img src=${filling.image} alt="" class="baked-img">
                                  </div>
                                </div> `
                              }

                        else {
                          content_container.innerHTML += `
                                <div class="single_content baked__left d-flex align-items-center justify-content-start">
                                  <div class="baked__left-img">
                                    <img src=${filling.image} alt="" class="baked-img">
                                  </div>
                                  <div class="baked__info d-flex flex-column">
                                    <h4 class="baked__title text-uppercase fw-bold">${filling.name}</h4>
                                    <p class="baked-info">
                                      Состав: ${filling.composition}
                                    </p>
                                  </div>
                                </div>` 
                        }

                })
                if (_current_item == total) {
                    
                } else {
                    loadBtn.classList.remove('not-visible');
                }
            },
            error: function (err) {
                console.log(err);
            },
        });
    }



    function loadmorePortfolio() {
      var _current_portfolio_item = $('.single_content_portfolio').length
      const content_container_portfolio = document.getElementById("port-content");
      $.ajax({
          url: '{% url "cakeapp:load" %}',
          type: 'GET',
          data: {
              'offset-portfolio': _current_portfolio_item
          },
          beforeSend: function () {
              loadBtnPort.classList.add('not-visible');
              spinnerPort.classList.remove('not-visible');
          },
          success: function (response) {
              const data = response.portfolio
              console.log(data)
              spinnerPort.classList.add('not-visible')
              data.map((portfolio) => {                 
                content_container_portfolio.innerHTML += `<img src=${portfolio.image}  alt="" class="single_content_portfolio work__content-img m-1" />`

              })
              if (_current_portfolio_item == totalPort) {
                  
              } else {
                loadBtnPort.classList.remove('not-visible');
              }
          },
          error: function (err) {
              console.log(err);
          },
      });
  }

    loadBtn.addEventListener('click', () => {
        loadmoreFilling()
    });

    loadBtnPort.addEventListener('click', () => {
      loadmorePortfolio()
    });
</script>



  <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

multicake/cakeapp/templates/filling.html
{% extends 'base.html' %}
{% load static i18n %}
{% block content %}


    <title>
        ВЫПЕЧКА ЛЮБОЙ СЛОЖНОСТИ НА ЗАКАЗ | Barcha turdagi pishiriqlarga buyurtma olamz
    </title>
<section class="baked" id="baked">
  <div class="container">
    <h2 class="product__title title">{% trans "Barcha turdagi pishiriqlarga buyurtma olamz" %}</h2>

    <div class="container">
      <div class="content" id="content2">
  
          {% for filling in fillings %}

          {% if forloop.counter|divisibleby:2 %}

          <div class="single_content2 baked__right d-flex align-items-center justify-content-end">
            <div class="baked__info1">
              <h4 class="baked__title text-uppercase fw-bold">{{ filling.name }}</h4>
              <p class="baked-info">
                Состав: {{ filling.composition }}
              </p>
            </div>
            <div class="baked__left-img">
              <img src="{{ filling.image.url }}" alt="" class="baked-img">
            </div>
          </div> 

          {% else %}

        <div class="single_content2 baked__left d-flex align-items-center justify-content-start">
          <div class="baked__left-img">
            <img src="{{ filling.image.url }}" alt="" class="baked-img">
          </div>
          <div class="baked__info d-flex flex-column">
            <h4 class="baked__title text-uppercase fw-bold">{{ filling.name }}</h4>
            <p class="baked-info">
              Состав: {{ filling.composition }}
            </p>
          </div>
        </div>

        {% endif %}

      {% endfor %}

      </div>
      <div class="spinner-border text-primary mt-2 not-visible" role="status" id="spinner-filling2">
          <span class="sr-only">Loading...</span>
      </div>
      <div class="load-more__btn mt-3" id="btn-filling2">
          <button type="button" class="load-button btn btn-danger">{% trans "Yana" %}</button>
      </div>
      <div class="alert alert-danger mt-2 not-visible" role="alert" id='alert-filling2'>
          {% trans "Boshqa qolmadi" %}
      </div>
  </div>
  {{total_fillings|json_script:"json-total2"}}

  </div>

</section>






<script>
  const loadBtn2 = document.getElementById('btn-filling2');
  const spinner2 = document.getElementById('spinner-filling2');
  const total2 = JSON.parse(document.getElementById('json-total2').textContent);
  const alert2 = document.getElementById('alert-filling2');



  function loadmoreFilling2() {
    var _current_item = $('.single_content2').length
    const content_container = document.getElementById("content2");
    $.ajax({
        url: '{% url "cakeapp:load" %}',
        type: 'GET',
        data: {
            'offset-4': _current_item
        },
        beforeSend: function () {
            loadBtn2.classList.add('not-visible');
            spinner2.classList.remove('not-visible'); 
        },
        success: function (response) {
            const data = response.fillings
            spinner2.classList.add('not-visible')
            data.map((filling, index) => {

                if (index%2 == 0) {
               
                  content_container.innerHTML += `

                            <div class="single_content2 baked__right d-flex align-items-center justify-content-end">
                              <div class="baked__info1">
                                <h4 class="baked__title text-uppercase fw-bold">${filling.name}</h4>
                                <p class="baked-info">
                                  Состав: ${filling.composition}
                                </p>
                              </div>
                              <div class="baked__left-img">
                                <img src=${filling.image} alt="" class="baked-img">
                              </div>
                            </div> `
                          }

                    else {
                      content_container.innerHTML += `
                            <div class="single_content2 baked__left d-flex align-items-center justify-content-start">
                              <div class="baked__left-img">
                                <img src=${filling.image} alt="" class="baked-img">
                              </div>
                              <div class="baked__info d-flex flex-column">
                                <h4 class="baked__title text-uppercase fw-bold">${filling.name}</h4>
                                <p class="baked-info">
                                  Состав: ${filling.composition}
                                </p>
                              </div>
                            </div>` 
                    }

            })
            if (_current_item == total2) {
                
            } else {
                loadBtn2.classList.remove('not-visible');
            }
        },
        error: function (err) {
            console.log(err);
        },
    });
}


  loadBtn2.addEventListener('click', () => {
    loadmoreFilling2()
  });

</script>


{% endblock %}